{"name": "test_create_user", "status": "failed", "statusDetails": {"message": "AssertionError: Expected <[<models.book_models.Book object at 0x0000021662AAB160>]> to be equal to <[]>, but was not.", "trace": "self = <tests.test_user.TestUsers object at 0x0000021662A32D60>\n\n    def test_create_user(self):\n        # Get user and verify that he have empty books collection\n        user = User.get_user_by_id(self.new_user_session, self.user_id)\n>       assert_that(user.books).is_equal_to([])\nE       AssertionError: Expected <[<models.book_models.Book object at 0x0000021662AAB160>]> to be equal to <[]>, but was not.\n\ntests\\test_user.py:14: AssertionError"}, "start": 1662885234996, "stop": 1662885235065, "uuid": "e4f32862-0298-4661-86d1-3826c0e389ad", "historyId": "31d905abdb7eaf2f4acb9faa50adf55a", "testCaseId": "0ee0df7a98def66e1af55aa4dc40c789", "fullName": "tests.test_user.TestUsers#test_create_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUsers"}, {"name": "host", "value": "DESKTOP-6B2AP20"}, {"name": "thread", "value": "15516-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user"}]}